# need to review if it's possible to slim down methods down to 10 LOCs
# and if not, either disable this cop inline or bump up limits. in any
# case once we're clear on max allowed LOCs per method - it should be
# fixed in rubocop config (as rubocop constantly changing "best practices"
# according to moon's phase and wind's direction).
Metrics/MethodLength:
  Exclude:
    - lib/sidekiq/throttled/strategy.rb
    - lib/sidekiq/throttled/queues_pauser.rb
    - lib/sidekiq/throttled/communicator/callbacks.rb
    - lib/sidekiq/throttled/communicator/listener.rb

# i have no strong feeling one way or the other, but probably using JSON for
# serializatino will be a bit more secure indeed.
Security/MarshalLoad:
  Exclude:
    - lib/sidekiq/throttled/communicator/listener.rb

# Enable this cop once we drop Ruby 2.2.x support.
Style/SafeNavigation:
  Enabled: false

# Enable this cop once we drop Ruby 2.2.x support.
Style/NumericPredicate:
  Enabled: false
