language: ruby
sudo: false

services:
  - redis-server

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler --no-rdoc --no-ri
  - bundle --version

install: bundle install --without development doc

env:
  - JRUBY_OPTS="$JRUBY_OPTS --debug" WITH_REDIS_NAMESPACE="false"
  - JRUBY_OPTS="$JRUBY_OPTS --debug" WITH_REDIS_NAMESPACE="true"

rvm:
  # Include JRuby first because it takes the longest
  - jruby-9.1.7.0
  - rbx-2
  - 2.2
  - 2.3.3
  - 2.4.0

matrix:
  fast_finish: true
  include:
    # Only run RuboCop and Yardstick metrics on the latest MRI
    - rvm: 2.4.0
      env: SUITE="rubocop"
      gemfile: Gemfile
    - rvm: 2.4.0
      env: SUITE="yardstick"
      gemfile: Gemfile

gemfile:
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile
  - gemfiles/sidekiq_4.2.gemfile
