language: ruby
sudo: false

services:
  - redis-server

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler --no-rdoc --no-ri
  - bundle --version

install: bundle install --without development doc

env:
  - WITH_REDIS_NAMESPACE="false"
  - WITH_REDIS_NAMESPACE="true"

rvm:
  - 2.2
  - 2.3.3
  - 2.4.0

matrix:
  fast_finish: true
  include:
    -
      rvm: 2.4.0
      env: SUITE="rubocop"
      gemfile: Gemfile
    -
      rvm: jruby-9.1.8.0
      env: JRUBY_OPTS="$JRUBY_OPTS --debug" WITH_REDIS_NAMESPACE="false"
      gemfile: Gemfile
    -
      rvm: jruby-9.1.8.0
      env: JRUBY_OPTS="$JRUBY_OPTS --debug" WITH_REDIS_NAMESPACE="true"
      gemfile: Gemfile
  allow_failures:
    -
      rvm: jruby-9.1.8.0

gemfile:
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile
  - gemfiles/sidekiq_4.2.gemfile
