language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
gemfile:
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile
  - gemfiles/sidekiq_latest.gemfile
env:
  - WITH_REDIS_NAMESPACE=0
  - WITH_REDIS_NAMESPACE=1
before_install:
  - gem install bundler -v 1.10.6
services:
  - redis-server
sudo: false
